# -*- coding: utf-8 -*-
"""
Serkan Can Caglayan 8/3/2020
Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BxhuMxj-edOmBBdxutXNRU5MejBhyORX

# NEURAL NETWORK ILE RAKAM SINIFLANDIRMA

# MNIST Data Set Yukleme
"""

from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

"""#YAPAY SINIR AGI MIMARISI"""

from keras import models #network modelleri
from keras import layers #network katmanlari

network = models.Sequential()
#giris layeri, 512 hucreli
network.add(layers.Dense(512, activation = 'relu', input_shape =(28 * 28, )))
#siniflandirici layer, 10 rakam oldugu icin 10 hucreli
network.add(layers.Dense(10, activation = 'softmax'))

"""#YAPAR SINIR AGI MODELININ DERLENMESI"""

network.compile(optimizer = 'rmsprop',
                loss = 'categorical_crossentropy',
                metrics = ['accuracy'])
    
"""#GIRISLERIN VE ETIKETLERIN HAZIRLANMASI"""

train_images = train_images.reshape((60000, 28 * 28))
#Normalize ediyoruz uint8 -> float32
train_images = train_images.astype('float32') / 255 

test_images = test_images.reshape((10000, 28 * 28))
#Normalize ediyoruz uint8 -> float32
test_images = test_images.astype('float32') / 255

from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

"""#NETWORKUN EGITILMESI"""

network.fit(train_images, train_labels, epochs = 5, batch_size = 128)

test_loss, test_acc = network.evaluate(test_images, test_labels)
print(test_loss, test_acc)